name: check

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Check formatting
        run: |
          unclean=$(gofmt -l ./cmd ./internal)
          [ -z "$unclean" ] || { echo "$unclean"; exit 1; }
      - run: go vet ./...
      - run: go test ./...
